name = "kitchen-rota"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "kitchen_rota_db"
database_name = "kitchen-rota-db"
database_id = "99124bfd-b257-4748-a220-e77a5793e7b0"
