name = "kitchen-rota"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "kitchen-rota-db"
database_id = "ce6502d2-2f6b-4041-be71-bd8c6886e375"
